### ISSUE TITLE
how could i get the assert 

### ISSUE THREAD

**Issue by ajenpan** [smartsl/biaori#1]
你好. 我需要 asserts 的资源. 我想问一下 方便提供/上传一下这个资源嘛. 
看readme页面上说 `正版用户可在 App 中下载数据后，拷贝手机存储设备中的 PEP/BiaoRi 目录到本目录下，改名为 assets ，来使用里面的音频等资源`
但是我不知道这个app是啥. 也没有android 设备. 不方便下载.

**Comment by smartsl** [comment]
https://play.google.com/store/apps/details?id=com.PEP.biaori&hl=en_US&gl=US
可以找个android模拟器下载

**Comment by ajenpan** [comment]
ok, tks
